### PR TITLE
B hub skulls

### PR DESCRIPTION
**Pull request by b-hub**
#763 Should hopefully resolve the issue raised by @Spooky-0

The bug was caused by a custom play order which removes knocked out players. However, when calculating the first() player during the initial_placement phase the order position returned used the old play order instead of the new custom play order. This meant in some cases the order position was out of range and ended up causing ctx.currentPlayer = undefined.

### CODE REVIEW

**Comment by Spooky-0** [comment]
Sweet! Glad to hear that you found (and fixed 👏) the bug!

**Comment by b-hub** [comment]
Thanks for your report @Spooky-0! Hopefully you can get a full game of 6 in now :)

**Comment by Spooky-0** [comment]
Btw one more issue - but I'm not sure if it is actually an issue: once when playing I had to turn cards up. But exactly then I had some internet issue. So I was able to turn over cards and see their value - bomb orbunny. I refreshed my browser and it was like nothing had happened - the cards were turned back. 
This is obviously a problem since players could easily cheat. 
Did you use the Hiden Game state machanic from boardgames.io? If not, it's very easy to implement. The only thing that might be a bit weird ist the game tests since there the tester (player1 for example) might not have access to the values.

Let me know if this is indeed the case and we can work on fixing it together

**Comment by flamecoals** [comment]
Great, thanks @b-hub !

**Review by flamecoals — APPROVED** [review]

**Pull request merged**
