### PR TITLE
Dracula2

### PR DESCRIPTION
**Pull request by Spooky-0**
#### Checklist

* [ ] Use a separate branch in your local repo (not `master`).
* [ ] Test coverage is 90% or better (or you have a story for why it's ok).

### CODE REVIEW

**Comment by flamecoals** [comment]
Can you fix the lint errors seen here:
https://travis-ci.com/github/freeboardgames/FreeBoardGames.org/builds/190692670

**Comment by flamecoals** [comment]
I left some comments. With the new contribution guidelines, we can merge the PR even though it isnt ready for users to play yet, and it might be missing some desired attributes (mobile ready, unit tests), etc.

**Comment by flamecoals** [comment]
Thanks for creating the todo! This is a great idea for keeping track of remaining work to be done. As soon as it passes CI we can merge

**Comment by flamecoals** [comment]
@Spooky-0 it seems like the lint is still failing for this PR:
https://travis-ci.com/github/freeboardgames/FreeBoardGames.org/jobs/403395515

if you want, you can run `cd web/ && yarn run lint` locally to check these errors. Also try `yarn run lint:fix`, but it will fix only a subset of them.

**Comment by Spooky-0** [comment]
> @Spooky-0 it seems like the lint is still failing for this PR:
> https://travis-ci.com/github/freeboardgames/FreeBoardGames.org/jobs/403395515
> 
> if you want, you can run `cd web/ && yarn run lint` locally to check these errors. Also try `yarn run lint:fix`, but it will fix only a subset of them.

Oh yea you mentioned it last time around already. I forgot to fix it...

**Comment by Spooky-0** [comment]
jeeez the amount linting things you guys want from me hahah! I'll fix it later.

But afaik the game now works. However, I have never been able to test it all the way to the end (as part of the game I must execute a player, and in a 2player game it leaves me in a deadlock...)

So I would like to see this as part of a development game pretty soon.
When I test it out with a few friends we can take it down from dev, i'll add tests and then we are good to go.

Frontend wise i'd like to do a few things, but not many. Just a bit of spacing , maybe a horizontal line here or there. THe only big thing I want is a Question Mark at the top, which pops up a dialog where all the symbols are explained. (since its not 100% obvious how Secret Hitler is interperted here).

let me know what you think :)

**Comment by cwatsonc** [comment]
> jeeez the amount linting things you guys want from me hahah! I'll fix it later.
> 

@Spooky-0 I don't CI will work unless you clear all linter errors (and warnings).  Let me know if you need any help

**Review by flamecoals — APPROVED** [review]

**Pull request merged**
