### PR TITLE
Unit tests for Bulls and Cows and minor UI mobile fixes

### PR DESCRIPTION
**Pull request by leocaseiro**
#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] I've read and agree with the [contribution guidelines](https://www.freeboardgames.org/docs/?path=/story/documentation-contributing--page).

I'm adding the unit tests, some minor fixes for iOS UI, and setting the game Bulls and Cows to published.

Please, let me know what else I should test.

I also refactored the Board in multiple components.

### CODE REVIEW

**Review by flamecoals — APPROVED** [review]
Looks Great, thanks!

**Comment by flamecoals** [comment]
I will let you know when this hits prod!

**Comment by leocaseiro** [comment]
Thank you for that. I appreciate it.

**Comment by flamecoals** [comment]
@leocaseiro Thanks! The game was launched and it is in production now :tada: !

Quick question: Any reason to not allow multiplayer mode ? It is the most common used mode in our games. So we might be a low hanging fruit for improving the game!

**Comment by leocaseiro** [comment]
I just think that this game as multiplayer it's kind of useless (the second player chooses the secret, and tells the 1st player what are correct and what are not, so I made a bot for it). 
Not sure if you ever played it.

I could try to setup some COOP version, but I'm not sure how would that work.

**Comment by flamecoals** [comment]
Oh, I see. So the way you built it is more like an AI, rather than you
sharing a device with a friend. Maybe we could change the game mode to AI,
so the card on the game page explains it correctly? What do you think?

**Pull request merged**
