### PR TITLE
[customization] Remove support of render methods from Customization

### PR DESCRIPTION
**Pull request by richardaum**
#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] I've read and agree with the [contribution guidelines](https://www.freeboardgames.org/docs/?path=/story/documentation-contributing--page).

### CODE REVIEW

**Comment by vdfdev** [comment]
Ugh, I did it again, didn't notice a PR wasn't for master. My bad.

**Comment by vdfdev** [comment]
We can merge both together now

**Comment by richardaum** [comment]
@vdfdev these failing tests you fixed should not be changed as the output expected is the translated value, not the key. Could you take a look why? Anyway, tomorrow I could take a look why it is happening also.

**Review by vdfdev — APPROVED** [review]

**Comment by vdfdev** [comment]
Oh, sorry, I thought that jest wouldn't translate them, so I thought it was
correct. I will check how you did with the regular tictactoe

**Pull request merged**
