### PR TITLE
Add some unit tests for the GameOver component.

### PR DESCRIPTION
**Pull request by mateusazis**
Please review some extra unit tests. I'm totally newbie on TS, so feel free to comment on anything :)

#### Checklist

* [X] Use a separate branch in your local repo (not `master`).
* [X] Test coverage is 90% or better (or you have a story for why it's ok).

### CODE REVIEW

**Comment by flamecoals** [comment]
Wow! thanks so much! We need to improve our testing, this is very helpful!

**Comment by flamecoals** [comment]
The linter failed, can you run `yarn run format` ?

**Comment by flamecoals** [comment]
This new test seem to be falling:
``
 FAIL  src/components/App/Game/GameOver.test.tsx
  ● GameOver › with all optional parameters › should render extra content.
    TestingLibraryElementError: Unable to find an element with the text: /fake-game-code/. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
``

You can test locally by doing:
``
cd web/
yarn run test --watch src/components/App/Game/GameOver.test.tsx
``

**Comment by mateusazis** [comment]
PTAL. I had added added some debug code... then tests for it </shamecube>.

**Pull request merged**
