### PR TITLE
It translation

### PR DESCRIPTION
**Pull request by migius**
#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] I've read and agree with the [contribution guidelines](https://www.freeboardgames.org/docs/?path=/story/documentation-contributing--page).

### CODE REVIEW

**Comment by vdfdev** [comment]
Looks great! Thank you!

**Comment by vdfdev** [comment]
Running into some errors on the test, I can take a look soon

**Comment by migius** [comment]
In my current environment I can't run test but I probably solved the problem.

**Review by vdfdev — APPROVED** [review]

**Comment by vdfdev** [comment]
Thanks! Will deploy this soon

**Pull request merged**
