### PR TITLE
Addition of ZooParade ,similar to Hanabi.

### PR DESCRIPTION
**Pull request by Spooky-0**
There are still a few Issues. Some of those I know how to fix, others I would like your help for. Thanks!

P.S. I just merged with master, and things still run :)

### CODE REVIEW

**Comment by flamecoals** [comment]
Some ideas to improve the UX. I will help develop with the features everybody agrees on.

* [ ] When it is the player's turn, show three buttons: Give a tip, Play a card, discard a card.
  - By clicking on each button, it shows a dialog with the cards to select or the color/number to select.
* [ ] Use the our PlayerBadge for showing which others are waiting on.
* [ ] The life counter could be little hearts [like minecraft](https://my.mcpedl.com/storage/texturepacks/1283/images/hardcore-hearts-_6.png)
* [ ] The number of "bones" should be on top of the image itself, so we can know what the number is about
* [ ] The number of cards on the deck should be on top of the image itself.
* [ ] When the player gives a tip, we should show an animation with a text like "Tip for flamecoals: Reds" and the slots of the color/number that are known should be highlighted.
* [ ] When the player plays a card, show a text like "Flamecoals played a card: SUCCESS", and highlight the card played. Play a win song or a defeat song in case of success/failure respectively.
* [ ] When the player discard a card, it should show a text like "Flamecoals discarded a card" and highlight the discard pile.

With the bullet points above, we can remove the text log on the right (it will be replaced by these announcements on the screen). So the game should have more than enough space to play on mobile (especially because the tap area will be only the 3 buttons with the possible actions and their dialogs).

**Comment by DanielSherlock** [comment]
> * [ ]  When it is the player's turn, show three buttons: Give a tip, Play a card, discard a card.
>   
>   * By clicking on each button, it shows a dialog with the cards to select or the color/number to select.

Does it need to be a separate dialog for the Play/Discard buttons? - could it not be more like in Take 6, when you just click on the thing you want (in Take 6 the card and then the pile, in this the card once you've clicked the button). Also there can be more than two players, in which case you have to choose which player to give the hint to. I'd previously thought about having the Play/Discard buttons next to your own cards, and then a Give Hint button next to each players cards?

> * [ ]  The life counter could be little hearts [like minecraft](https://my.mcpedl.com/storage/texturepacks/1283/images/hardcore-hearts-_6.png)

I had had a similar thought!

> * [ ]  The number of "bones" should be on top of the image itself, so we can know what the number is about
> * [ ]  The number of cards on the deck should be on top of the image itself (i.e. x34).

I believe that was always @Spooky-0's plan, I've just not got round to it yet.

> * [ ]  When the player gives a tip, we should show an animation with a text like "Tip for flamecoals: Reds" and the slots of the color/number that are known should be highlighted.
> * [ ]  When the player plays a card, show a text like "Flamecoals played a card: SUCCESS", and highlight the card played. Play a win song or a defeat song in case of success/failure respectively.
> * [ ]  When the player discard a card, it should show a text like "Flamecoals discarded a card" and highlight the discard pile.

I think @Spooky-0 mentioned having these announcements, and I made space for them in my UI. I think this is a good idea.

> With the bullet points above, we can remove the text log on the right (it will be replaced by these announcements on the screen). So the game should have more than enough space to play on mobile (especially because the tap area will be only the 3 buttons with the possible actions and their dialogs).

So apparently the logs are kind of important for more advanced play, because they mean the players can see the hints in context and get more nuance from them. However, in my UI so far, they are hidden by default because I think most players won't want to use them. They also don't mess with the scrolling. Obviously, keeping them means we will have to put in some work making them prettier, but @Spooky-0 had some great ideas for that.

**Comment by DanielSherlock** [comment]
Aside from UI decisions, here are some other things that I'm aware of that need to be done:

- [ ] Card values: We should change the cards and hints to show 1-5 instead of 0-4. This is not hard.
- [ ] Rule fix: The players should be given an extra "bone token" when they complete a set of animals (place a 5). @Spooky-0 might have done this already I'm not sure?
- [ ] Hint deduction: At the moment, the cards don't use all of the information they can to figure out / show what they can and can't be. I've already coded this change, I just need to merge it.

**Comment by Spooky-0** [comment]
> 
> 
> Aside from UI decisions, here are some other things that I'm aware of that need to be done:
> 
>     * [  ]  Card values: We should change the cards and hints to show 1-5 instead of 0-4. This is not hard.
Yes, very easy! But its nice to have 0-4 for debugging, since it the lines up with the array index.

>     * [ ]  Rule fix: The players should be given an extra "bone token" when they complete a set of animals (successfully play a 5). @Spooky-0 might have done this already I'm not sure?
Done!

>     * [ ]  Hint deduction: At the moment, the cards don't use all of the information they can to figure out / show what they can and can't be. I've already coded this change, I just need to merge it.
I think this should be done in the frontend only! Its very easy to do. We can just show a black square everywhere else if we have a signle '1' in the hint somewhere. If there is just '0' and '-1' we use the old method.

**Comment by flamecoals** [comment]
Thanks for the comments @DanielSherlock  and @Spooky-0. I made some mocks with my ideas. Feel free to comment on them.

How the UI could look on mobile:
image

User selecting a card for playing or discard:
image

User giving a tip:
image

Quick announcement to all players of tip given (and highlighted tip):
image

Quick announcement to all players of card played (and highlighted card):
image

Quick announcement to all players of card discarded (and highlighted card):
image

Here are the drawings, you can leave comments there too:
https://docs.google.com/drawings/d/13L6yLtMZy88TQb55ODE4eY3RPyUrwU6yvyQc0Ujik8A/edit

Let me know what you like/dont like/want to change. It will be fun and I can help building this :)

**Comment by flamecoals** [comment]
And @DanielSherlock, regarding the logs, we can probably hide them in FBG bar menu, like we have in Seabattle:
image
image

**Comment by Spooky-0** [comment]
> 
> 
> > * [ ]   When it is the player's turn, show three buttons: Give a tip, Play a card, discard a card.
> >   
> >   * By clicking on each button, it shows a dialog with the cards to select or the color/number to select.
> 
> Does it need to be a separate dialog for the Play/Discard buttons? - could it not be more like in Take 6, when you just click on the thing you want (in Take 6 the card and then the pile, in this the card once you've clicked the button). Also there can be more than two players, in which case you have to choose which player to give the hint to. I'd previously thought about having the Play/Discard buttons next to your own cards, and then a Give Hint button next to each players cards?
> 

I like the approach of clicking a card and then having the play/discard option.
For the hints, the issue is that you can give a hint to each player for each color or number. So thats 10 possibilites per player! The way that hanabi.live does it, is you select a player and then give a hint. I've played with friends and they accedently gave wrong hints. I don't like it very much how they do it. So i thought it would be nicer to show all of the buttons - its cluttered but you don't make mistakes.
> > * [ ]   Use our PlayerBadge component for showing which player turn is.
> 
> Sure.
> 
> > * [ ]   The life counter could be little hearts [like minecraft](https://my.mcpedl.com/storage/texturepacks/1283/images/hardcore-hearts-_6.png)
> 
> I had had a similar thought!
> 
> > * [ ]   The number of "bones" should be on top of the image itself, so we can know what the number is about
> > * [ ]   The number of cards on the deck should be on top of the image itself (i.e. x34).
> 
> I believe that was always @Spooky-0's plan, I've just not got round to it yet.
> 

100% i just dont know how to 'overlay' things :).

> > * [ ]   When the player gives a tip, we should show an animation with a text like "Tip for flamecoals: Reds" and the slots of the color/number that are known should be highlighted.

The last hint could be additionally highlighted. Since its not obvious from the game state what the last hint was, it might be necessary to add this to the Game object. I think this is a feature for post v1.0 realse.

> > * [ ]   When the player plays a card, show a text like "Flamecoals played a card: SUCCESS", and highlight the card played. Play a win song or a defeat song in case of success/failure respectively.

Im not a fan of sounds xD. As long as there is a mute button I dont' mind xD.

> > * [ ]   When the player discard a card, it should show a text like "Flamecoals discarded a card" and highlight the discard pile.

Agreed. Once all discarded cards are shown, the last discarded card should be highlighted. Same goes for the last played card.
This goes hand in hand with the highlighting the last hint.

> 
> I think @Spooky-0 mentioned having these announcements, and I made space for them in my UI. I think this is a good idea.
> 
> > With the bullet points above, we can remove the text log on the right (it will be replaced by these announcements on the screen). So the game should have more than enough space to play on mobile (especially because the tap area will be only the 3 buttons with the possible actions and their dialogs).
> 
> So apparently the logs are kind of important for more advanced play, because they mean the players can see the hints in context and get more nuance from them. However, in my UI so far, they are hidden by default because I think most players won't want to use them. They also don't mess with the scrolling. Obviously, keeping them means we will have to put in some work making them prettier, but @Spooky-0 had some great ideas for that.

Yes, logs are important. Its important to know whether the hint from 11 moves ago was before/after the hint from 10 moves ago. For mobile there should just be a 'show logs' since you dont always need to see them.

I will send a picture in DC soon to show you what I imageine for the Desktop version.

**Comment by Spooky-0** [comment]
Oh you already added mocs! I like them alot.

Two things:
 I would like to put the 5 number and color boxes ONTOP of the cards. That localizes them and then you have less cluttered little boxes.

When you press the trash on mobile you should see all trashed cards.
For desktop, you can see all of them all the time.

Apart from that its perfekt

**Comment by flamecoals** [comment]
Ok! I like your suggestions! I am going to sleep now, tomorrow I can update
the mocks with them

**Comment by DanielSherlock** [comment]
> I like the approach of clicking a card and then having the play/discard option.
> For the hints, the issue is that you can give a hint to each player for each color or number. So thats 10 possibilites per player! The way that hanabi.live does it, is you select a player and then give a hint. I've played with friends and they accedently gave wrong hints. I don't like it very much how they do it. So i thought it would be nicer to show all of the buttons - its cluttered but you don't make mistakes.

I also like the idea of clicking on the actual cards. For the hints, I have an idea for a possible compromise but it's hard to explain.

> Im not a fan of sounds xD. As long as there is a mute button I dont' mind xD.

I think that's sensible.

**Comment by DanielSherlock** [comment]
> > * [  ]  Card values
> 
> Yes, very easy! But its nice to have 0-4 for debugging, since it the lines up with the array index.

Sure. I just wanted to add it to the list, also so that @flamecoals knows we plan to eventually do that.

> > * [ ]  Rule fix
> 
> Done!

Excellent!

> > * [ ]  Hint deduction
> 
> I think this should be done in the frontend only! Its very easy to do. We can just show a black square everywhere else if we have a signle '1' in the hint somewhere. If there is just '0' and '-1' we use the old method.

I mean, as I say, I've already done it, it just needs to be merged - so very easy indeed! (At the moment, the changes I made are in the [zp-hint-logic](https://github.com/DanielSherlock/FreeBoardGames.org/tree/zp-hint-logic) branch of my fork. The branch is still on the old version, and I'm having some laptop troubles but I'll get it merged soon enough.)

**Comment by DanielSherlock** [comment]
> Thanks for the comments @DanielSherlock and @Spooky-0. I made some mocks with my ideas. Feel free to comment on them.
> 
> Let me know what you like/dont like/want to change. It will be fun and I can help building this :)

These look cool. I would be entirely happy to play the game if it looked like that. Still, I can't help have some things I want to change.

I didn't expect the player badges to be at the bottom, I thought they would replace the names by the cards. Also, I presume the score number will be removed?

Also, there's a balance to strike between clutter and being able to see everything while making your decision. I think this is also what @Spooky-0 is talking about when they say they want the hints not to be so separate. So far I've been strongly prioritising seeing everything at once, and your mock-ups have convinced me that a few dialog boxes aren't so bad, but I still think a lot of the time we can get away without them without extra clutter.

> When you press the trash on mobile you should see all trashed cards.
> For desktop, you can see all of them all the time.

Yup. That behaviour is already in my UI work so far.

**Comment by DanielSherlock** [comment]
> I would like to put the 5 number and color boxes ONTOP of the cards. That localizes them and then you have less cluttered little boxes.

This is the one think I'm still not 100% sure it will work. Still, it's worth trying. Another option to reduce visual clutter might be to get rid of the brown borders on the hints / make them into circles?

**Comment by flamecoals** [comment]
Here is the updated mock with some of your suggestions:
image

The squares inside each card could probably be made bigger, but I had a hard time with this tool for creating this mocks.
My main concern is that this option of having 11 buttons for the user to select (5 discards and 5 plays + 1 give a tip) will NOT work on mobile, as the tap target would be too small. Maybe we can show these buttons only on desktop, and on mobile go with the 3 buttons approach. What do you think?

**Comment by flamecoals** [comment]
Hey @DanielSherlock, no luck merging your changes? If you want I can help you tomorrow

**Comment by Spooky-0** [comment]
Hi, 
I was on holiday for a few days, back now and have a whole free day tomorrow :)
I like the mockup! Maybe we can even have the trash cards form a row at the top. So now there is just a giraffe-4, but imagine like a bunch more filling up from left to right as you discard more. Then you can always see them.
The little info squares need to be bigger ofc. But this is kinda what I imagined, i think it should work.
And I also agree that there are two many clickable things at the bottom. I think if we press a card, a new dialog should open for [play / discard].
If you click another players card a dialog opens to give that player a hint - as you already had suggested in the older mockup.

**Comment by flamecoals** [comment]
Sounds good! I like your suggestions!

**Comment by flamecoals** [comment]
Hey, I didnt forget about ZooParade, I am just finishing some key infrastructure changes that will unblock us to do some important features (like lobby and text chat). I am almost done with it, so I will get back to ZooParade soon

**Comment by flamecoals** [comment]
Hey folks, I was busy finishing the lobby, now that we merged that I will be focusing on this :)

**Comment by Spooky-0** [comment]
Hey! Thats great to hear!
Since html+css is my nemisis I don't really know what I can do for this projet.

**Comment by flamecoals** [comment]
@DanielSherlock I merged the work you've done on your layout branch, I couldn't do it automatically because of so many conflicts, so I might have missed something. Nevertheless I think I got most of the work you've done.

I couldn't merge your "tips" branch because it seemed to have some error, the tests were failing, so it wasnt a simpler refactor.

I am going to add some storybooks stories for this game now, to allow me to understand better the code structure, and then I will start finishing the layout, so we can merge soon.

**Comment by DanielSherlock** [comment]
> @DanielSherlock I merged the work you've done on your layout branch, I couldn't do it automatically because of so many conflicts, so I might have missed something. Nevertheless I think I got most of the work you've done.
> 
> I couldn't merge your "tips" branch because it seemed to have some error, the tests were failing, so it wasnt a simpler refactor.
> 
> I am going to add some storybooks stories for this game now, to allow me to understand better the code structure, and then I will start finishing the layout, so we can merge soon.

Firstly, sorry to you both for disappearing for so long like that. Personal reasons mean I can't fully rule out something similar, but I will at least try to let you know what's up if it happens again.

I'm very impressed you managed to manually merge my layout changes - I was still struggling to get the newer version running on my laptop before. I think I will have to try a completely clean setup and see if that helps. Once that's working, I will re-implement the _tips_ stuff (it wasn't much work, and I've done it already). I will have to ask you for help understanding the tests if it makes them fail again, as I'm completely new to all that.

**Comment by flamecoals** [comment]
No need to apologise @DanielSherlock, I am also doing this on my spare time for fun, so no pressure :).

I saw your tips code, and because it should be a refactor, the tests should not be impacted. As it started failing, ithat means there was some error on the refactor that changed the code behavior.... I would just try to see what changed...

I am going to try to make some progress this weekend, I want to have the menus and etc done by then

**Comment by flamecoals** [comment]
I made good progress today, this ish ow it looks on desktop:
image

And on mobile:
image

The logs can be toggled on the menu bar.

Tomorrow I will add the "notification" where we alert the user of the latest action (as we dont have animations right now, I find this necessary to be playable). And a simple unit test for the UI (to make sure it renders)... And we should be able to launch it :)

**Pull request merged**
