### PR TITLE
Estate Buyer - Similar to For Sale

### PR DESCRIPTION
**Pull request by ryandriskel**
This is an implementation of the game "For Sale" as shown here https://www.youtube.com/watch?v=OZ0RLgnBp6o 

This is a WIP PR as I have not written tests. I am looking for help first finding omissions.

Note: During the second phase, when playing online play, the card you select can be changed until the moment everyone has selected a card.

#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [ ] Test coverage is 90% or better (or you have a story for why it's ok).

### CODE REVIEW

**Comment by flamecoals** [comment]
Wow, thanks for this! I will have a look into it later, (I Need to learn the rules first hahaha).

Let me know if you need any help at all! I am a bit busy finishing https://github.com/freeboardgames/FreeBoardGames.org/pull/601 and then finishing https://github.com/freeboardgames/FreeBoardGames.org/pull/505 but hopefully by the time you have it ready for review I will be ready too :)

**Comment by jasonharrison** [comment]
Great work with the UI and the animations!  Thank you @ryandriskel !  Let us know if you need any help.

Really minor thing: I noticed that "yet" in "no cards yet" hangs over:
"yet" hangs over
"yet" hangs over

**Comment by ryandriskel** [comment]
> Really minor thing: I noticed that "yet" in "no cards yet" hangs over

Good catch, thank you! I originally had a different font in there, but then found it only worked on machines with that font installed. I tried to get a custom font to load but had trouble with the webpack config. I could get the font to load in storybook but not in a real game.

I'll review the font choices overall again.

**Comment by flamecoals** [comment]
Sorry I took so long to look into this PR again. But I am amazed by the progress you made!
Incredible animations, sound, everything! I will review the code ASAP and we can merge and push soon this weekend.

**Comment by flamecoals** [comment]
FYI, I was discussing with @jasonharrison and we are going to be a bit more lax on the rules about unit tests. It will be in the lines of:

- We will require high test coverage only for the rules, as this is where most of the complex logic lives.
- We will require only one unit test for the UI, to make sure it renders. You already have this.
- In lieu of unit tests for the UI, games can use storybook. You already have several stories :).

Overall, I think this PR can be merged. I will just review the code to see if there isn't any obvious improvement.

Again, sorry for taking so long to review your PR. I had some problems with the changes caused by covid and etc, but I am back to normal now :)

**Comment by flamecoals** [comment]
@jasonharrison and another friend played tonight and we are extremely impressed with the game, congratulations @ryandriskel !

We found some minor bugs that made the game hard to play for some of us:
- The red font with the blue background made it impossible for a colorblind person to see
- The money selection did not work properly on Android. If you pressed backspace to remove the existing value and type hte new one, the code would automatically replace with the maximum bid.
- The money left/total rent collected (on the green backgroudn on the user badge) did not display the value on mobile, probably because of lack of space.

I will fix these bugs tomorrow and we can merge :D

**Comment by flamecoals** [comment]
So, the font bug was because there was no fallback font, added monospace for that. The money selection bug was because the component wouldnt accept no value in the field, fixed that too. And changed the red font to white to be more colorblind-friendly.

**Review by flamecoals — APPROVED** [review]

**Pull request merged**
