### PR TITLE
stay in turn on matches

### PR DESCRIPTION
**Pull request by sefgit**
adapted rules to stay in turn on matches
youtube's video id updated to refer to new rules
test cases updated accordingly

#### Checklist

* [X] Use a separate branch in your local repo (not `master`).
* [X] I've read and agree with the [contribution guidelines](https://www.freeboardgames.org/docs/?path=/story/documentation-contributing--page).

### CODE REVIEW

**Comment by flamecoals** [comment]
Hi @sefgit, welcome to FBG! I will add @gk-patel as a reviewer because he was the author of the game, so he is more familiar with the code base.

Meanwhile, it seems like the CI failed with this error:
``
>5:10  warning  'selectHttpOptionsAndBody' is defined but never used  @typescript-eslint/no-unused-vars
``

Can you take a look?

**Comment by sefgit** [comment]
> Hi @sefgit, welcome to FBG! I will add @gk-patel as a reviewer because he was the author of the game, so he is more familiar with the code base.
> 
> Meanwhile, it seems like the CI failed with this error:
> 
> > 5:10  warning  'selectHttpOptionsAndBody' is defined but never used  @typescript-eslint/no-unused-vars
> 
> Can you take a look?

Thank you for prompt reply. 
Indeed I missed the unused import. :(
Fixed in the latest commit.

Thank you for this great free boardgame platform.
Looking forward to contribute more in my spare time.

**Comment by gk-patel** [comment]
Hi @sefgit  

Welcome to FBG ! Very nice to see others are motivated by my game and like to improve it. 

Actually when I was programming this game, I had a choice to make and I decided to chagen turns even if the player finds a match. What you have proposed here is something I also considered, but at the end I decided to go with my implementation. 

The reason why I choose not to implement as you propose was, many times at the very end I found that one player get a huge advantage over the other. I have no mathematics to prove that this (your) approach is baised. On the other hand my approach is unbaised (because if both perform equal, then the game is a draw). Nevertheless, my wife does complain to me that more than 50% of the time the game is a draw and asks me to do something about it. lol. 

Once again I really appreciate your changes, and I dont want to be the one who discourages you to take initiative. Moreover, I also dont want the game to be baised. But because, I cannot prove that your approach is baised, lets do one thing -  we make a VOTE is the discord group and we decide based on the first 10 votes. 

OR @flamecoals this can be a paramter that can be injected, just like hard/easy. 

So for now, we leave this PR open and wait for sometime.

**Comment by sefgit** [comment]
> Hi @sefgit
> 
> Welcome to FBG ! Very nice to see others are motivated by my game and like to improve it.
> 
> Actually when I was programming this game, I had a choice to make and I decided to chagen turns even if the player finds a match. What you have proposed here is something I also considered, but at the end I decided to go with my implementation.
> 
> The reason why I choose not to implement as you propose was, many times at the very end I found that one player get a huge advantage over the other. I have no mathematics to prove that this (your) approach is baised. On the other hand my approach is unbaised (because if both perform equal, then the game is a draw). Nevertheless, my wife does complain to me that more than 50% of the time the game is a draw and asks me to do something about it. lol.
> 
> Once again I really appreciate your changes, and I dont want to be the one who discourages you to take initiative. Moreover, I also dont want the game to be baised. But because, I cannot prove that your approach is baised, lets do one thing - we make a VOTE is the discord group and we decide based on the first 10 votes.
> 
> OR @flamecoals this can be a paramter that can be injected, just like hard/easy.
> 
> So for now, we leave this PR open and wait for sometime.

Thank you for your prompt reply.
No doubt you've considered the original rules as you mentioned.
Thanks to your decision to implement as it is with your clean and clear code, it gave me opportunity to learn FBG.
A new parameter easy/hard for the gave as you suggested would be great. I would like to learn how this can be implemented.
An easier method would be to fork as additional similiar game ;)
Thanks again for the opportunity to participate.

**Comment by flamecoals** [comment]
Hey folks!

Yes, i am working in adding capabilities of customizing/configuring rules
for each game, so this is a perfect use case/example for it! I am already
50%ish on the feature, so whenever I merge the PR I can come back here and
adapt the rules to work that way!

What do you think? We can leave the PR open and I will do the changes when
it is time

**Comment by flamecoals** [comment]
@sefgit and check our Discord, we have a little community there of developers and are always helping each other and chatting about life 🤣

**Comment by sefgit** [comment]
Excellent, no rush, take your time. 
Looking forward to add more games here.
Meanwhile I shall install discord app now.

Thanks @flamecoals

**Comment by flamecoals** [comment]
Let's leave it open so we don't lose the code :)

**Comment by flamecoals** [comment]
Good news @sefgit and @gk-patel , the infra-structure to allow rules customization is done! You can read about it here:
https://www.freeboardgames.org/docs/?path=/story/documentation-game-customization--page

I am going to change this PR on the next few days to allow users to configure this parameter (stay in turn or not when there is a match) on the settings of the game.

**Comment by sefgit** [comment]
quite occupied lately. Thanks for the excellent work.

**Comment by flamecoals** [comment]
No worries, I have been busy too, moving houses. I hope next weekend I might have some time for looking into this PR.

**Comment by vdfdev** [comment]
Hey, I didnt forget about this PR, it is just that my attention has been on some other issues, but I will see if I can find some time to use the new game customization framework to support this change in rules.

**Review by vdfdev — APPROVED** [review]

**Comment by vdfdev** [comment]
Ok folks, the customization option is implemented now :D. I let the default be to stay in turn on matches, I think this variation of the rule is probably regional and there is not a truly "right" or "wrong"... I used to play staying in turn as a child, so I am a bit biased letting this be the default :P. Anyway, now users can change easily (and whatever they choose is sticky for them) :)

**Pull request merged**
