### PR TITLE
Rename hotels chains in Mergers

### PR DESCRIPTION
**Pull request by lfkellogg**
**NOTE**: To avoid merge conflicts, this change was made on top of https://github.com/freeboardgames/FreeBoardGames.org/pull/689. After merging that PR, rebase this one on master.

Renames the hotel chains to help avoid any IP issues.

#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] I've read and agree with the [contribution guidelines](https://www.freeboardgames.org/docs/?path=/story/documentation-contributing--page).

### CODE REVIEW

**Review by flamecoals — APPROVED** [review]

**Comment by flamecoals** [comment]
Uh. It seems like there are some conflicts, so I can't fast forward to HEAD... Can you take a look?

**Comment by lfkellogg** [comment]
@flamecoals Woops, yeah sure, taking a look.

**Comment by lfkellogg** [comment]
@flamecoals Resolved. I just tested it out locally too and everything looks good 👍

**Comment by lfkellogg** [comment]
Actually I messed up part of that merge and left some old CSS in there. Just fixed it. Should be good now.

**Pull request merged**
